package:
    name: nrel-phygnn
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy>=1.16
    - pandas
    - matplotlib
    - scikit-learn
    - tensorflow
  run:
    - python
    - pip
    - setuptools
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib
    - scikit-learn
    - tensorflow

about:
  home: "https://github.com/NREL/phygnn"
  license: BSD 3-Clause
  summary: "Physics-Guided Neural Networks (phygnn)"
  doc_url: "https://nrel.github.io/phygnn/"
  dev_url: "https://github.com/NREL/phygnn"
