name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.4.10
          args: check --output-format=github
          src: "./phygnn ./tests"
